name: Run NSE Data Greeks Notebook

on:
  workflow_dispatch:  # Allows manual triggering from GitHub

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Fetches your repo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Modify version if needed

    - name: Install Dependencies
      run: |
        pip install jupyter nbconvert pandas numpy requests  # Install required packages

    - name: Debug - Before Running Script
      run: |
        echo "Current Working Directory:"
        pwd
        echo "Files in the Directory:"
        ls -la

    - name: Convert Notebook to Python Script (if needed)
      run: |
        if [ -f "nse_options.ipynb" ]; then
          jupyter nbconvert --to script nse_options.ipynb
        fi

    - name: Run the Python Script
      run: python nse_options.py  # Executes the updated script

    - name: Debug - After Running Script
      run: |
        echo "Files in the Directory (After Execution):"
        ls -la

    - name: Upload Output Files
      uses: actions/upload-artifact@v4  # ✅ Updated version
      with:
        name: nse_output
        path: |
          *.csv
          *.json
          *.txt
