name: Run NSE Data Greeks Notebook

on:
  workflow_dispatch:  # Allows you to manually trigger this workflow from GitHub

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Fetches your repo so we can access the notebook

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Change Python version if needed

    - name: Install Dependencies
      run: |
        pip install jupyter nbconvert pandas numpy requests  # Install required packages

    - name: Debug - Before Running Notebook
      run: |
        echo "Current Working Directory:"
        pwd
        echo "Files in the Directory:"
        ls -la

    - name: Convert Notebook to Python Script
      run: jupyter nbconvert --to script nse_data_greeks.ipynb  # Converts to a .py script

    - name: Run the Converted Python Script
      run: python nse_data_greeks.py  # Executes the script

    - name: Debug - After Running Notebook
      run: |
        echo "Files in the Directory (After Execution):"
        ls -la

    - name: Upload Output Files
      uses: actions/upload-artifact@v3
      with:
        name: nse_output
        path: |
          *.csv
          *.json
          *.txt
